baseURL: https://williamsport.recoverysource.io/
title: Greater Williamsport AA

languageCode: en-us
theme: [williamsport, aamod, mainroad]
paginate: 100
buildFuture: true

Params:
  description: Greater Williamsport Area (District 53) Alcoholics Anonymous
  source: https://github.com/recoverysource/williamsport
  #mapapikey: <https://developers.google.com/maps/documentation/embed/get-api-key>
  mapapikey: "AIzaSyB5hKG5VIASVlBBaDjNXUYxmw3CR_wSzLY"
  copyright: Greater Williamsport Area AA
  phone: 570-666-1448
  logo:
    image: img/AAlogo.png
    title: Greater Williamsport Area AA
    subtitle: Area 59 District 48 - Eastern Pennsylvania General Service Assembly
  toc: true
  mainSections: [home, meetings, about, events]
  sidebar:
    single: right
    home: right
    widgets: [resources, eventsidemenu, aasites]
  widgets:

    resources:
      cached: true
      links:
      - title: Meeting Schedule
        url: /meeting-schedule.pdf
      - title: Big Book Online
        url: https://www.aa.org/bigbookonline/

    aasites:
      cached: true
      links:
      - title: District 48 Business
        url: /business/
      - title: District 48 History
        url: /history/
      - title: Helpful Documents
        url: /documents/
      - title: Area 59 (Eastern PA)
        url: https://area59aa.org/
      - title: A.A. World Services
        url: https://www.aa.org/
      - title: A.A. Grapevine
        url: http://www.aagrapevine.org/

markup:
  goldmark:
    renderer:
      # Permit raw HTML in content
      unsafe: true
